services:
  l2d:
    build:
      context: .
      dockerfile: DockerFile
    image: l2d:latest
    working_dir: /workspace
    stdin_open: true
    tty: true
    environment:
      HF_TOKEN: -
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,utility
    volumes:
      - .:/workspace
    command: /bin/bash
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
